### ISSUE TITLE
请问benchmark代码中，在测试过程，每一个turn对应的三元组是如何得到的？

### ISSUE THREAD

**Issue by HuihuiChyan** [thu-coai/KdConv#10]
作者您好！因为tensorflow不是很熟悉，所以这个问题希望您可以帮忙确认一下。
在训练过程，seq2seq模型中，每一个turn对应的三元组使用的是训练集已经标注好的。
在测试过程中，每一个turn对应的三元组是如何得到的呢？也使用已经标注好的吗？

**Comment by chujiezheng** [comment]
benchmark中，是以memory unit的形式储存整个session涉及到的三元组，然后解码时用attention读取。训练和测试都是这样

一个可能更适合的做法是从kb中检索出相关的三元组使用，而非直接使用数据集里标注好的三元组
