### ISSUE TITLE
论文中有写测试时的PPL值，在测试代码中找不到PPL值

### ISSUE THREAD

**Issue by jiaweimmiao** [thu-coai/KdConv#11]
首先很感谢作者公开的代码以及数据集，仔细拜读了您的论文，本人十分受启迪，再次谢谢您~
但是在复现作者代码时出现些小问题，HRED模型训练后，在测试时，困惑度（PPL）指标值并没有找到代码实现部分，看到了Blue值，distinct值实现部分，并能得到其具体值。
本人有两个问题：
1）论文中提到的PPL是指验证时，在验证数据集得到结果值，还是在测试数据集上得到。
2）如果是在测试时得到，困惑度指标值代码可以公开嘛？
恳请您的回复，谢谢！

**Comment by chujiezheng** [comment]
ppl利用了cotk包中的实现，我们的代码在这里导入：`myCoTK/dataloader/single_turn_dialog.py` 中line 12的PerplexityMetric

**Comment by chujiezheng** [comment]
可以参考[这里](https://github.com/thu-coai/KdConv/blob/e44876c298302633875e9c22244af39f723d9afb/benchmark/seq2seq/myCoTK/dataloader/multi_turn_dialog.py#L154)

**Comment by jiaweimmiao** [comment]
十分感谢老师，刚刚怕您GitHub上看不到，正在给您写邮件刚写到一半，没想到这么晚还回复我。我现在试一试。那论文中PPL值是在测试集进行测试得到的吧？




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Chujie Zheng"<notifications@github.com&gt;; 
发送时间: 2021年1月6日(星期三) 晚上10:15
收件人: "thu-coai/KdConv"<KdConv@noreply.github.com&gt;; 
抄送: "幸福就好"<455605116@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [thu-coai/KdConv] 论文中有写测试时的PPL值，在测试代码中找不到PPL值 (#11)





 
可以参考这里

**Comment by chujiezheng** [comment]
是的，代码里有写清楚，可以参考[这里](https://github.com/thu-coai/KdConv/blob/e44876c298302633875e9c22244af39f723d9afb/benchmark/hred/model.py#L312)

**Comment by jiaweimmiao** [comment]
老师您是说这块代码实现了PPL嘛？



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Chujie Zheng"<notifications@github.com&gt;; 
发送时间: 2021年1月6日(星期三) 晚上10:12
收件人: "thu-coai/KdConv"<KdConv@noreply.github.com&gt;; 
抄送: "幸福就好"<455605116@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [thu-coai/KdConv] 论文中有写测试时的PPL值，在测试代码中找不到PPL值 (#11)





 
ppl利用了cotk包中的实现，我们的代码在这里导入：myCoTK/dataloader/single_turn_dialog.py 中line 12的PerplexityMetric

**Comment by chujiezheng** [comment]
是

**Comment by jiaweimmiao** [comment]
老师您在回复中指出的那个链接里是有关于PPL实现的页面，PPL主要是通过下面代码实现吧？
但这块代码
print('    perplexity on %s set: %.2f' % (key_name, np.exp(loss)))
print(loss)
return loss
是在evaluate函数中写的，那意味着得到的PPL是验证集而非测试集的啊。






------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Chujie Zheng"<notifications@github.com&gt;; 
发送时间: 2021年1月6日(星期三) 晚上10:49
收件人: "thu-coai/KdConv"<KdConv@noreply.github.com&gt;; 
抄送: "幸福就好"<455605116@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [thu-coai/KdConv] 论文中有写测试时的PPL值，在测试代码中找不到PPL值 (#11)





 
是

**Comment by chujiezheng** [comment]
在测试的时候，调用[这个](https://github.com/thu-coai/KdConv/blob/e44876c298302633875e9c22244af39f723d9afb/benchmark/hred/model.py#L310)方法，然后通过[metric1](https://github.com/thu-coai/KdConv/blob/e44876c298302633875e9c22244af39f723d9afb/benchmark/hred/model.py#L312)得到计算ppl的Metric类，通过[导入](https://github.com/thu-coai/KdConv/blob/e44876c298302633875e9c22244af39f723d9afb/benchmark/hred/model.py#L322)测试时的模型输出，最后通过[close方法](https://github.com/thu-coai/KdConv/blob/e44876c298302633875e9c22244af39f723d9afb/benchmark/hred/model.py#L338)计算ppl值
