### ISSUE TITLE
[memhred] NameError: `kg_num_mask` is not defined

### ISSUE THREAD

**Issue by BorisPolonsky** [thu-coai/KdConv#16]
### Steps to replicate
`#./train_travel.sh`

### Log
```
NameError: name 'kg_num_mask' is not defined
```
### Source:
https://github.com/thu-coai/KdConv/blob/e44876c298302633875e9c22244af39f723d9afb/benchmark/memhred/model.py#L135

**Comment by chujiezheng** [comment]
I have fixed it. Thank you!
