### ISSUE TITLE
Cannot find chinese_wwm_pytorch

### ISSUE THREAD

**Issue by KristenZHANG** [thu-coai/KdConv#17]
Hi, I encountered a problem when running the code in benchmark/bertret and want to seek your help. It seems that the 'chinese_wwm_pytorch' cannot be found, including all related files (/vocab.txt, /added_tokens.json etc.):
<img width="946" alt="Screenshot 2021-06-22 093836" src="https://user-images.githubusercontent.com/31750614/122849247-b9498100-d33d-11eb-9ccc-f850e5d74fad.png">

Another weird problem is when running ./train_film(music, travel) in other models except bert, like LM andseq2seq, I always encountered the segmentation fault and didnt figure out the reason:
![image](https://user-images.githubusercontent.com/31750614/122849489-3117ab80-d33e-11eb-853b-4592bd544f11.png)

Thanks so much!

**Comment by chujiezheng** [comment]
1. You should prepare the pretrained model, such as from https://huggingface.co/hfl/chinese-bert-wwm-ext
2. I am not sure the causes. Maybe you can use another python version like 3.6. I guess that the different versions of libraries (such as pytorch and tensorflow) may also lead to the problem

**Comment by KristenZHANG** [comment]
Hi chujie, thanks so much for your reply.

The problem2 has been solved by changing the python version to 3.6.

For problem1, I tried to download the **BERT-wwm-ext** from the link and it only contains 3 files: bert_config.json, pytorch_model.bin and vocab.txt
![image](https://user-images.githubusercontent.com/31750614/123616666-17440000-d839-11eb-8aa0-1ec96a3415fb.png) 
![image](https://user-images.githubusercontent.com/31750614/123616837-40fd2700-d839-11eb-8ce8-fe818defa120.png)
and after downloading it, when I tried to run train_film.sh in bertret folder, it shows the following:
![image](https://user-images.githubusercontent.com/31750614/123617050-730e8900-d839-11eb-8917-557b7c7b8f74.png)

I want to ask 
1) is it normal that **added_tokens.json, special_tokens_map.json, tokenizer_config.json** are not found? 
2) there is no **chinese_stop_words.txt** (**resources** folder) in data, did I miss any step?

Thanks so much!

**Comment by chujiezheng** [comment]
1. It is normal. The new version of transformers will try to load these files, but the earlier models do not have these files. So feel free to ignore the warnings.
2. You can download a stop word list like this: https://github.com/goto456/stopwords
