### ISSUE TITLE
How to find the corresponding KG for each dialogue

### ISSUE THREAD

**Issue by freesunshine0316** [thu-coai/KdConv#3]
Hi, 
Very interesting task. We find out that the knowledge bases are separated from the dialogues, while each turn is associated with a specific piece of knowledge.
Are the dev/test sets also associated with the specific knowledge piece?

Lastly, please upload the devset, it shouldn't been held out.

**Comment by freesunshine0316** [comment]
Hi @chujiezheng 

Can you please look into this? Thanks.

**Comment by chujiezheng** [comment]
> Are the dev/test sets also associated with the specific knowledge piece?

Yes

> Lastly, please upload the devset, it shouldn't been held out.

We will upload all the data after that the competition finishes.
