### ISSUE TITLE
What is the  "self.key_name" in the benchmark code? Is the test/dev data that you did not give?

### ISSUE THREAD

**Issue by Mrwhite132613** [thu-coai/KdConv#5]
for key in self.key_name:
            origin_data[key] = {'posts': [], 'prev_posts': [], 'responses': [], 'kg': [], 'kg_index': []}

**Comment by Mrwhite132613** [comment]
thanks
@chujiezheng

**Comment by chujiezheng** [comment]
It is a list of dataset split names, such as ['train', 'dev', 'test']. They are also the data file names.

**Comment by Mrwhite132613** [comment]
@chujiezheng 可以加一个微信吗？这个benchmark感觉有好多地方跑不通。这个数据集您只给了train.json，是dev和test要从train.json里面自己切分吗？数据集超级nice,也是刚刚做对话，想交个朋友，十分感谢

**Comment by chujiezheng** [comment]
可以的，您把您的联系方式发到我的邮箱：zcj16@tsinghua.org.cn，我添加您

由于我们现在在办比赛，所以dev和test会推迟些公开
