### ISSUE TITLE
what's the version of CoTK? could you provide it?

### ISSUE THREAD

**Issue by data-science-studio** [thu-coai/KdConv#6]
trying to run the membertret model, but have several errors about CoTK pakcage.

**Comment by data-science-studio** [comment]
the cotk package is installed by 'pip3 install cotk'

**Comment by chujiezheng** [comment]
cotk==0.0.1

You can find requirements [here](https://github.com/thu-coai/KdConv/blob/master/benchmark/requirements.txt)

**Comment by data-science-studio** [comment]
thanks
