### ISSUE TITLE
What is test_distractors.json？

### ISSUE THREAD

**Issue by 27182812** [thu-coai/KdConv#9]
![image](https://user-images.githubusercontent.com/33630730/97782415-63687300-1bcc-11eb-9fc6-3bb95c3ec87e.png)
I met this issue, could you tell me what is test_distractors.json and where is it? 
Thank you very much!

**Comment by chujiezheng** [comment]
You can find the creation process of `*_distractors.json` at line 89 in the file `myCoTK/dataloader/bert_dataloader.py`

**Comment by 27182812** [comment]
我才发现原来可以中文，就是我运行了memseq2seq还有LM都是这样，训练好了，调用测试的时候会报上述那个错误，bert_dataloader.py在测试里面好像并没有运行，是指我要先去运行这个吗？

**Comment by chujiezheng** [comment]
是的，你需要先运行bert相关模型来生成distractor。用seq2seq或LM等跑distractor是为了从中选择PPL（或者loss）最低的回复。如果不需要这部分实验，只要注释掉就可以了。

**Comment by DesmonDay** [comment]
啊 想问。。 感觉数据集很乱，好像在 test.json 也没有标明我们需要预测回复的语句是什么？还是说每一段对话都自己分成多个测试样例么

**Comment by chujiezheng** [comment]
可以参考这个

https://smp2020.aconf.cn/smp.html#3
